apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: annotate-seccomp-pod-runtime
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    excludedNamespaces: [
      "calico-apiserver",
      "calico-system",
      "cert-manager",
      "concourse",
      "gatekeeper-system",
      "ingress-controllers",
      "kube-system",
      "kuberos",
      "logging",
      "monitoring",
      "smoketest-psp-*",
      "smoketest-psa-*",
      "tigera-operator",
      "trivy-system",
      "velero",
      "cloud-platform-canary-app-eks"
      ]
  location: 'metadata.annotations."seccomp.security.alpha.kubernetes.io/pod"'
  parameters:
    assign:
      value:  "runtime/default"

