apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: default-seccomp-profile
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    excludedNamespaces: [
      "calico-apiserver",
      "calico-system",
      "cert-manager",
      "concourse",
      "gatekeeper-system",
      "ingress-controllers",
      "kube-system",
      "kuberos",
      "logging",
      "monitoring",
      "smoketest-psp-*",
      "smoketest-psa-*",
      "tigera-operator",
      "trivy-system",
      "velero",
      "cloud-platform-canary-app-eks",
      "hmpps-adjustments-preprod",
      "hmpps-adjustments-prod",
      "hmpps-incentives-prod",
      "hmpps-launchpad-prod",
      "hmpps-locations-inside-prison-prod",
      "hmpps-non-associations-prod",
      "hmpps-person-record-prod",
      "hmpps-prisoner-from-nomis-migration-prod",
      "hmpps-prisoner-search-dev",
      "hmpps-prisoner-search-prod",
      "hmpps-restricted-patients-api-prod",
      "laa-apply-for-legalaid-uat",
      "offender-case-notes-prod",
      "whereabouts-api-prod"
      ]
  location: "spec.securityContext.seccompProfile.type"
  parameters:
    pathTests:
    - subPath: "spec.securityContext.seccompProfile.type"
      condition: MustNotExist
    assign: 
      value: "RuntimeDefault"

