apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: default-seccomp-profile
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    excludedNamespaces: [
      "cloud-platform-label-pods",
      "calico-apiserver",
      "calico-system",
      "cert-manager",
      "concourse",
      "gatekeeper-system",
      "ingress-controllers",
      "kube-system",
      "kuberos",
      "logging",
      "monitoring",
      "smoketest-psp-*",
      "smoketest-psa-*",
      "tigera-operator",
      "trivy-system",
      "velero",
      "cloud-platform-canary-app-eks"
      ]
  location: "spec.securityContext.seccompProfile.type"
  parameters:
    pathTests:
    - subPath: "spec.securityContext.seccompProfile.type"
      condition: MustNotExist
    assign: 
      value: "RuntimeDefault"

