apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: drop-all-cap-init
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    excludedNamespaces: [
      "calico-apiserver",
      "calico-system",
      "cert-manager",
      "concourse",
      "gatekeeper-system",
      "ingress-controllers",
      "kube-system",
      "kuberos",
      "logging",
      "monitoring",
      "smoketest-psp-*",
      "smoketest-psa-*",
      "tigera-operator",
      "trivy-system",
      "velero",
      "amazon-guardduty",
      "cilium*"
      ]
  location: "spec.initContainers[name:*].securityContext.capabilities.drop"
  parameters:
    assign:
      value:
        - "ALL"

