apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jacksapp-dev
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: sec-ctx-demo
        image: busybox:1.28
        command: [ "sh", "-c", "sleep 15m" ]
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
