apiVersion: v1
kind: Pod
metadata:
  namespace: starter-pack-0
  name: nginx
spec:
  containers:
    - image: nginx:latest
      name: nginx
      ports:
        - containerPort: 80
      securityContext:
        allowPrivilegeEscalation: true
        runAsUser: 0

