apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8svalidhostname
metadata:
  name: k8svalidhostname
spec:
  match:
    kinds:
      - kinds: ["Ingress"]
        apiGroups: ["extensions", "networking.k8s.io"]
  parameters:
    validDomainNames: "*.update.this.fqdn.value,*.example.com"

