apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sdenydefaultmodsec
metadata:
  name: k8sdenydefaultmodsec
spec:
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]