apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sallowduplicatehostname
metadata:
  name: allow-duplicate-hostname
spec:
  match:
    kinds:
      - kinds: ["Ingress"]
        apiGroups: ["extensions", "networking.k8s.io"]
