apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LockPrivCapabilities
metadata:
  name: lockprivcapabilities
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: [
      "calico-apiserver",
      "calico-system",
      "cert-manager",
      "concourse",
      "gatekeeper-system",
      "kuberos",
      "logging",
      "monitoring",
      "smoketest-psa-*",
      "trivy-system",
      "velero"
      ]
    excludedNamespaces: [
      "ingress-controllers",
      "kube-system",
      "kube-node-lease",
      "kube-public",
      "tigera-operator"
      ]
  parameters:
    allowedCapabilities: ["NET_BIND_SERVICE","NET_ADMIN"]
    requiredDropCapabilities: ["NET_RAW"]