apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sservicetypeloadbalancer
metadata:
  name: k8sservicetypeloadbalancer
spec:
  match:
    excludedNamespaces: ["ingress-controllers"]
    kinds:
      - kinds: ["Service"]

