apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: user-ns-require-psa-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    excludedNamespaces: [
      "calico-apiserver",
      "calico-system",
      "cert-manager",
      "concourse",
      "gatekeeper-system",
      "ingress-controllers",
      "kube-system",
      "kube-node-lease",
      "kube-public",
      "default",
      "kuberos",
      "logging",
      "monitoring",
      "smoketest-psp-*",
      "smoketest-psa-*",
      "tigera-operator",
      "trivy-system",
      "velero",
      "amazon-guardduty",
      "cilium*"
      ]
  parameters:
    message: "All user namespaces must have a `pod-security.kubernetes.io/enforce: restricted` label."
    labels:
    - key: pod-security.kubernetes.io/enforce
      allowedRegex: restricted
